is_local = !ENV["CI"]
local_android_key = "/Users/condomaker/Documents/projects-lesson/react-native/PipelineApp/android/app/uTask.keystore"

android_project_dir = "./android"
android_signing_key = is_local ? local_android_key : ENV["ANDROID_SIGNING_KEY"]
android_signing_alias = is_local ? "uTask" : ENV["ANDROID_SIGNING_ALIAS"]
android_signing_password = is_local ? "arch123" : ENV["ANDROID_SIGNING_PASSWORD"]

android_properties = {
  "android.injected.signing.store.file" => android_signing_key,
  "android.injected.signing.store.password" => android_signing_password,
  "android.injected.signing.key.alias" => android_signing_alias,
  "android.injected.signing.key.password" => android_signing_password
}

platform :android do

  desc "Build debug APK"
  lane :buildDebug do
    gradle(task: "assembleDebug", project_dir: android_project_dir)
  end

  desc "Build release APK"
  lane :buildRelease do
    gradle(
      task: "assembleRelease",
      project_dir: android_project_dir,
      properties: android_properties
    )
  end
end
