is_server = ENV["CI"]
puts "Debug: is_server = #{is_server}"

android_project_dir = "./android"

android_properties = {
  "android.injected.signing.store.file" => ENV["ANDROID_SIGNING_KEY"],
  "android.injected.signing.store.password" => ENV["ANDROID_SIGNING_PASSWORD"],
  "android.injected.signing.key.alias" => ENV["ANDROID_SIGNING_ALIAS"],
  "android.injected.signing.key.password" => ENV["ANDROID_SIGNING_PASSWORD"]
}

platform :android do

  desc "Build debug APK"
  lane :buildDebug do
    gradle(task: "assembleDebug", project_dir: android_project_dir)
  end

  desc "Build release APK"
  lane :buildRelease do
    puts "Debug: ANDROID_SIGNING_ALIAS = #{ENV["ANDROID_SIGNING_ALIAS"]}"
    puts "Debug: ANDROID_SIGNING_PASSWORD = #{ENV["ANDROID_SIGNING_PASSWORD"]}"
    gradle(
      task: "assembleRelease",
      project_dir: android_project_dir,
      properties: android_properties
    )
  end

  desc "Bundle release .aab"
  lane :bundleRelease do
    puts "Debug: ANDROID_SIGNING_ALIAS = #{ENV["ANDROID_SIGNING_ALIAS"]}"
    puts "Debug: ANDROID_SIGNING_PASSWORD = #{ENV["ANDROID_SIGNING_PASSWORD"]}"
    puts "Debug: is_server = #{is_server}"
    gradle(
      task: "bundleRelease",
      project_dir: android_project_dir,
      properties: android_properties
    )
  end
end
