name: build
run-name: Build app uTask
on:
  push:
    branches:
      - development

jobs:
  build-android:
    name: Build Android Debug
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install project dependencies
        run: yarn install

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Install fastlane
        run: bundle install

      - name: Build debug android app
        run: bundle exec fastlane android buildDebug